### ISSUE TITLE
Last Phalcon 3.4.4-1 build failed

### ISSUE THREAD

**Issue by SentryXSI** [journeyman88/copr-repositories#1]
Hi Marco.   

In Fedora 31 the Phalcon copr repo cannot be installed due to build errors. 

```
phalcon | 3.4.4-1 | 2 months ago | failed 
```
https://copr.fedorainfracloud.org/coprs/mbignami/phalcon/build/1040488/
https://copr.fedorainfracloud.org/coprs/mbignami/phalcon/package/phalcon/

Thanks !!

**Comment by journeyman88** [comment]
That seems to be a problem compiling the RHEL8 version (which since it has a php7 release I thought to be able to compile it together with Fedora).

The most recent builds seems to have an issue with the init of the mock environment for fedora 30 i386
